add_languages("cxx20")
add_requires("xsimd")

target("tbase64")
    set_kind("headeronly")
    add_headerfiles("include/TBase64.hpp")
    add_packages("xsimd")
target_end()

target("MainTest")
    set_kind("binary")
    add_files("src/main.cpp")
    add_deps("tbase64")
    add_includedirs("include")
    add_packages("xsimd")
target_end()

target("BenchMark")
    set_kind("binary")
    add_files("src/benchmark.cpp")
    add_deps("tbase64")
    add_includedirs("include")
    add_packages("xsimd")
target_end()