add_languages("cxx20")

target("tbase64")
    set_kind("headeronly")
    add_headerfiles("include/TBase64.hpp")
target_end()

target("MainTest")
    set_kind("binary")
    add_files("src/main.cpp")
    add_deps("tbase64")
    add_includedirs("include")
target_end()

target("BenchMark")
    set_kind("binary")
    add_files("src/benchmark.cpp")
    add_deps("tbase64")
    add_includedirs("include")
target_end()